### ISSUE TITLE
Share MonsterViewModel

### ISSUE THREAD

**Issue by uhooi** [uhooi/UhooiPicBook-Android#124]
## Overview

Remove the following ViewModels:

- `MonsterDetailViewModel`
- `DancingMonsterViewModel`

Share the following ViewModel:

- `MonsterListViewModel` → `MonsterViewModel`

## References

- https://developer.android.com/guide/navigation/navigation-nested-graphs?hl=ja&authuser=1
- https://developer.android.com/training/dependency-injection/hilt-jetpack#viewmodel-navigation
- https://star-zero.medium.com/navigation-graphスコープのviewmodel-8bcfebca8c13
- https://star-zero.medium.com/nested-navigationとsafeargs-8f259ab4fbdd
- https://twitter.com/the_uhooi/status/1392488757073350665?s=20
- https://twitter.com/the_uhooi/status/1384490993383141378?s=20
- https://qiita.com/you03/items/de40eb51e16f74e3971d

**Comment by bassga** [comment]
これやってもよきー？
どんな感じでやりたいか正直まだわかっていないけどw

**Comment by uhooi** [comment]
アサインしているのは自分でやりたいやつなんよねwww
あ、でも方針は教えてもらった通り MonsterList と MonsterDetail で ViewModel を共有しようと考えている！
レビューしてくれるとありがたい 🙏
