### ISSUE TITLE
Introduce ktlint

### ISSUE THREAD

**Issue by yutailang0119** [uhooi/UhooiPicBook-Android#179]
Hi,
I feel that this project is organized by lints.
I think it works even better with [ktlint](https://ktlint.github.io).

Why don't you consider introducing it?

**Comment by uhooi** [comment]
I think detekt and Android Lint are sufficient for static analysis, and Android Studio for formatting.

However, I think it's a good idea to introduce it, so I'm waiting for your PR!!
