### ISSUE TITLE
Add splash screen

### ISSUE THREAD

**Issue by uhooi** [uhooi/UhooiPicBook-Android#45]
## References

- https://developer.android.com/about/versions/12/splash-screen-migration
- https://twitter.com/NabeCott/status/1319442820273377280?s=20  
> ActivityではなくNavigationでスプラッシュ画面の表示と遷移をすることになるので、最近はあまりしない手段な気もします 🤔 
- https://twitter.com/_rmakiyama/status/1319446549886201857?s=20  
> スプラッシュのためのActivityは最近見なくなりましたね〜

**Comment by galemu2** [comment]
I think this can also be closed.  I have added a splash screen that also functions as Launcher activity.

**Comment by uhooi** [comment]
Sorry, the splash screen will be implemented at another time :(

**Comment by uhooi** [comment]
Splash is now standard in Android 12, so close this issue.
