### ISSUE TITLE
Fix Deprecated method

### ISSUE THREAD

**Issue by shinya-takano** [uhooi/UhooiPicBook-Android#66]
This issue is so light issue.

use 'coil.api.load' to 'coil.load'

<img width="792" alt="スクリーンショット 2020-10-13 9 08 11" src="https://user-images.githubusercontent.com/2821692/95800970-cb493d80-0d33-11eb-9987-233baf0e2233.png">

Fix ViewBindingAdapters, MonsterDetailFragment

**Comment by shinya-takano** [comment]
iOSDCでuhooiさんのことを知り、uhooiPicBookにandroidもあると知り、コントリビュートしてみました。
コードを書く機会を探していて、いくつかプロダクトを探しているのですが、継続的にコントリビュート可能でしたら嬉しいです。
個人開発であまりIssueやPR求めていない場合はコメントいただけると幸いです。

普段はAndroidエンジニアしています。

**Comment by uhooi** [comment]
@shinya-takano 
おおおおお！！！とても嬉しいです 😄

**Comment by uhooi** [comment]
READMEの一番後ろにも書いたのですが、IssueやPRなどはいつでも誰でも大歓迎です！
（ただしAndroidは知識が少ないので、難しいPRはレビューに時間がかかる可能性があります）

今回のような軽微なご指摘でしたら、もちろんIssueだけでも嬉しいですし、直接PRを頂いても嬉しいです :)

Issueは「easy」や「good first issue」のラベルが付いているのが特にPR大歓迎です！

**Comment by uhooi** [comment]
ref: https://github.com/coil-kt/coil/blob/1bf3a576d5a46ec6cf97ec902ad1ca3d638fdef1/CHANGELOG.md#0120---august-18-2020

> __Important__: Coil's `ImageView` extension functions have been moved from the `coil.api` package to the `coil` package.
Use find + replace to refactor `import coil.api.load` -> `import coil.load`. Unfortunately, it's not possible to use Kotlin's `ReplaceWith` functionality to replace imports.
