### ISSUE TITLE
Prevent `MainActivity` from being called by other apps

### ISSUE THREAD

**Issue by uhooi** [uhooi/UhooiPicBook-Android#68]
References:

- https://developer.android.com/guide/topics/manifest/service-element?hl=ja#exported
- https://www.jssec.org/dl/android_securecoding.pdf  
p.31

AndroidManifest.xml

```diff
        <activity
            android:name=".MainActivity"
-             android:screenOrientation="portrait">
+             android:screenOrientation="portrait"
+             android:exported="false" />
```

**Comment by galemu2** [comment]
Hay, Can i Work on this?

**Comment by uhooi** [comment]
@galemu2 OK!!
I am waiting for your PR :)

**Comment by galemu2** [comment]
I think adding splash screen can help. Make splash screen as launcher activity then we can make 'MainActivity' inaccessible.  I used app name for splash screen.  If you prefer we can use image.

**Comment by uhooi** [comment]
Sorry, I was mistaken.
When `android:exported="false"` is set, the app will not be able to start.
This issue is closed.
