### ISSUE TITLE
こうしたい要望(メモ書き)

### ISSUE THREAD

**Issue by bassga** [uhooi/UhooiPicBook-Android#75]
- DateKtのMagicNumberのチェックは外してもいいかもしれない。
    -  理由は不要にvaluesで数字の管理をしないといけないって状態になりそうだから。
- coroutine使いたい。
- Timber入れてログ吐かさせたい

**Comment by uhooi** [comment]
@bassga 
こういうの言ってくれる人なかなかいないからめっちゃありがたい…！

> - DateKtのMagicNumberのチェックは外してもいいかもしれない。
>   - 理由は不要にvaluesで数字の管理をしないといけないって状態になりそうだから。

これはオレも思っていたので取り急ぎ Issue を立てた！ (#78)

> - coroutine使いたい。

オレも使いたいけど何もわからない、、
とりあえず Issue は立てたので PR ください :) (#79)

> - Timber入れてログ吐かさせたい

ログのライブラリなのか！
Issue を立てた！メリットを教えてくれると嬉しいかも 👍  (#80)

**Comment by uhooi** [comment]
すべて Issue 化したので、問題なければこの Issue はクローズするね！
